enum ResponseCode {
  SUCCESS = "SUCCESS",
  VALIDATION_FAIL = "VLF",
  DUPLICATE_ID = "DI",
  DUPLICATE_EMAIL = "DE",
  NO_SESSION_INFO = "NSI",
  SIGN_IN_FAIL = "SIF",
  NO_EMAIL = "NE",
  MAIL_SEND_FAIL = "MSF",
  VERIFICATION_FAIL = "VRF",
  DATABASE_ERROR = "DBE",
  NO_PERMISSION = "NP",
}
export default ResponseCode;
